### ISSUE TITLE
Tenant specific components

### ISSUE THREAD

**Issue by saileshkush95** [apal21/Vue.js-VueRouter-multiple-subdomains#7]
How can I specify tenant specific components.

**Comment by apal21** [comment]
Didn't get the question. Can you please tell this in detail?

**Comment by saileshkush95** [comment]
I mean i want to build multitenant application, using vue. My requirements is,
ui may be tenant specific or different.

**Comment by apal21** [comment]
Check this function: https://github.com/apal21/Vue.js-VueRouter-multiple-subdomains/blob/master/src/main.js#L15

Here we're checking the subdomain. You need to modify your if-else conditions according to your requirements. It can be at the domain or subdomain level.
